export const FACTS = [
  'The average American uses 650 pounds of paper each year. If all this paper was recycled, we could save up to 100 million tons of wood every year.',
  'Plastic bags and Styrofoam containers take up to thousands of years to decompose.',
  'If just one person goes vegan, they can save approximately 219,000 gallons of water a year.',
  'When you leave your computer monitors on overnight they emit 9 million tons of carbon dioxide every year.',
  'We need to reduce carbon dioxide emissions by humans to 45% from 2010 levels by 2030 and reach net-zero by 2050 to avoid a climate change catastrophe.',
  'Cycling 10 kilometers each way to work can save you about $1,700 in transport costs but most importantly, you will save the world 1,500 kilograms of greenhouse gas emissions every year.',
  '78% of marine mammals are at risk of choking on plastic.',
  'A glass bottle can take up to 1 million years to decompose.',
  'Paper from trees can be recycled 6 times. ',
  'The Great Pacific Garbage Patch is a twisting and turning vortex composed of trash and waste. It is twice the size of continental America and contains about 100 million tons of garbage, it stretches from the West Coast of North America to Japan along the Pacific Ocean.',
  'Seaweed Might Be The Food Of The Future: versatile, nutritious, and grow quickly compared to land crops.',
  'China And The USA Are The TOP Polluters In The World.',
  'The South African province of Mpumalanga has large coal power plants, which is why it has the highest air pollution level in the world. ',
  'Energy accounts for at least 60% of the total emission of global greenhouse gases.',
  '70% of our planet is covered by water. However, out of 70 percent, only 2.5 percent is fresh and what is accessible for human use is 1%. ',
  'We’ve added nearly 2.4 trillion tons of CO2 into the atmosphere. Half of this huge amount was emitted in the last 35 to 50 years.  ',
  'A Small Number Of Countries Are The Major Emitters: The USA, China, Canada, Russia, India, and Japan accounted for over 70% of the energy-related carbon dioxide emission in 2004.  ',
  'Germany has the best recycling rate. Other countries such as Austria, South Korea, and Wales follow closely. ',
  'Climate campaigners worldwide gathered to organize the first climate strike in March 2019. More than 1.6 million folks took part.',
  'When landfilled, the organic matter produces 34 times more powerful methane gas than CO2, leading to climate change.',
  'Local Food Saves Fossil Fuel Energy (because fewer energy-intensive transportation, packaging, ...',
  'The Most Eco-Friendly Country Is Denmark.',
  'Textile production contributes more to climate change than international aviation and shipping combined (House of Commons Environmental Audit Committee (UK), 2019)',
  'Fast fashion brands like SHEIN, REVOLVE, and Romwe all score less than 10% on the Fashion Transparency Index (2023).',
  '16 out of 21 items from 10 fashion brands donated through their take-back schemes were either destroyed, left in warehouses or exported to Africa, where up to half of used clothing are quickly shredded for other uses or dumped. (Changing Markets Foundation, 2023)',
  'Plastic particles washed off from products such as synthetic clothes contribute up to 35% of the primary plastic that is polluting our oceans. Every time we do our laundry an average of 9 million microfibers are released into wastewater treatment plants that cannot filter them. (Ocean Clean Wash, 2023)',
  'The Average Person Only Wears 20% of Their Clothes 80% of the Time.',
  '60% of Clothes Are Made With Plastic-based Materials.',
  'According to the United Nations Environment Programme (UNEP), 20% of global wastewater comes from textile dyeing alone. ',
  'In America alone, the average person throws away around 81 pounds (37kg) of clothing yearly. This leads to a staggering 85% of textile produced in the country ending up in landfills or being burned. ',
  'More than USD$500 Billion Are Lost from Lack of Recycling and Clothing Underutilisation.',
  '59% of All Sustainability Claims by European Fashion Brands Are Inaccurate and Misleading so please do some background research on these claims before purchasing them!',
  'Carbon capture and storage technology pulls carbon from the atmosphere and uses it to make synthetic fuel. ',
  'Upcycling is part of the circular economy, a model where ‘waste’ doesn’t exist — it simply becomes the raw material for something new.',
  'Companies find that investments like solar power can significantly reduce their energy consumption (and therefore energy costs) over the long-term, and finding eco-conscious suppliers can also lead to savings.',
  '70% of shoppers believe brands should be sustainable and environmentally responsible',
  "A PC with a screensaver going can use well over 100W of power, compared with only about 10W in sleep mode. That's why powering down PCs in your home or office makes more sense from both an environmental and cost-saving perspective.",
  'Although e-waste accounts for only 1 to 4 percent of municipal waste, it may be responsible for as much as 70 percent of the heavy metals in landfills, including 40 percent of all lead.',
  "The term greenwashing was coined by suburban New York environmentalist Jay Westerveld in 1986. He used the word in an essay in regard to the hotel industry's practice of placing placards in each room promoting reuse of guest towels to save the environment. He argued that the hotel industry was doing little or nothing else to help the environment and that playing on guests' environmental consciences to reuse towels was merely a ploy to save money.",
  'People who live in places with high levels of air pollutants have a 20% higher risk of death from lung cancer than people who live in less-polluted areas.',
  'Approximately 40% of the lakes in America are too polluted for fishing, aquatic life, or swimming.',
  'Each year 1.2 trillion gallons of untreated sewage, stormwater, and industrial waste are dumped into US water.',
  'More than 1 billion people worldwide don’t have access to safe drinking water.',
  '5000 people die every day as a result of drinking unclean water.',
  'More than 3 million kids under the age of 5 years die every year due to environmental factors like pollution.',
  'Almost 80% of urban waste in India is dumped in the river Ganges.',
  'Noise pollution is the most neglected type of pollution.',
  'The amount of money invested in the nuclear test could be used to finance 8,000 hand pumps, giving villages across the third world access to clean water.',
  'Acidification of the ocean is the worst type of pollution. Oceans are becoming more acidic due to greenhouse emissions from fossil fuels.',
  'More than 100 pesticides in any medium – air, water or soil can cause birth defects, gene mutation, and cancer.',
  'There are more than 73 various kinds of pesticides in the groundwater, which is used as drinking water.',
  'Major oil spills like those in the Gulf of Mexico, is the worst type of pollution due to consistent oil spills in the water body, which spreads everywhere else.',
  'There are more than 500 million cars in the world, and by 2030 the number will rise to 1 billion. This means the pollution level will be more than double.',
  'World Health Organization (WHO) estimates 6400 people die every year in Mexico due to air pollution.',
  'If Americans recycled just one-tenth of their newspapers, we would save 25 million trees a year.',
  'Producing one ton of paper from recycled pulp saves 17 trees, 3 cubic yards of landfill space & 7000 gallons of water. It also reduces air pollutants by 60 pounds, saves 390 gallons of oil & conserves 4200 kilowatt hours of energy – enough to heat a home for half a year.',
  'Not only do electric vehicles cost less to travel the same distance as a car run on fuel in an EV, but they have faster acceleration, and are powered by up to 80% of battery energy compared to fuel-powered vehicles — which only use between 14-16%.',
  'Australia is leading the way with green hydrogen.',
  'Wind power is the fastest growing form of electricity.',
  'Community gardens and farmers markets are the way to grow.',
  'Wetlands are the most biodiverse of all ecosystems.',
  'You can offset your carbon emissions from your flight by purchasing carbon credits that will later counterbalance your carbon footprint.'
]
